import type { Product, Service } from "@/types";

/** Static demo catalog metadata — image URLs come from CMS `demo_products_json` / `demo_services_json`. */
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-phone-case-premium",
    slug: "phone-case-premium",
    name_en: "Premium Phone Case",
    name_bn: "প্রিমিয়াম ফোন কেস",
    description_en: "Shock-absorbing TPU case with raised bezels for screen protection.",
    description_bn: "স্ক্রিন প্রটেকশনসহ শক-অ্যাবজর্বিং টিপিইউ কেস।",
    price: 299,
    original_price: 500,
    category: "accessories",
    badge: "HOT",
    stock_quantity: 50,
    is_featured: true,
    rating: 4.8,
    review_count: 124,
  },
  {
    id: "demo-fast-charger-65w",
    slug: "fast-charger-65w",
    name_en: "Fast Charger 65W",
    name_bn: "ফাস্ট চার্জার ৬৫W",
    description_en: "GaN fast charger with dual USB-C ports for phones and laptops.",
    description_bn: "ফোন ও ল্যাপটপের জন্য ডুয়াল USB-C পোর্টসহ GaN ফাস্ট চার্জার।",
    price: 599,
    original_price: 800,
    category: "accessories",
    badge: "SALE",
    stock_quantity: 30,
    is_featured: true,
    rating: 4.7,
    review_count: 89,
  },
  {
    id: "demo-earbuds-tws-pro",
    slug: "earbuds-tws-pro",
    name_en: "Earbuds TWS Pro",
    name_bn: "ওয়্যারলেস ইয়ারবাড প্রো",
    description_en: "Active noise cancellation with 24-hour total battery life.",
    description_bn: "২৪ ঘণ্টা ব্যাটারি লাইফসহ অ্যাক্টিভ নয়েজ ক্যানসেলেশন।",
    price: 999,
    original_price: 1500,
    category: "gadgets",
    badge: "NEW",
    stock_quantity: 20,
    is_featured: true,
    rating: 4.9,
    review_count: 203,
  },
  {
    id: "demo-power-bank-20000",
    slug: "power-bank-20000",
    name_en: "Power Bank 20000mAh",
    name_bn: "পাওয়ার ব্যাংক ২০০০০mAh",
    description_en: "High-capacity power bank with 22.5W fast charging support.",
    description_bn: "২২.৫W ফাস্ট চার্জিং সাপোর্টসহ হাই ক্যাপাসিটি পাওয়ার ব্যাংক।",
    price: 1299,
    category: "gadgets",
    stock_quantity: 15,
    is_featured: true,
    rating: 4.6,
    review_count: 67,
  },
  {
    id: "demo-glass-protector",
    slug: "glass-protector",
    name_en: "Tempered Glass Protector",
    name_bn: "টেম্পার্ড গ্লাস প্রটেক্টর",
    price: 250,
    category: "accessories",
    stock_quantity: 100,
    rating: 4.5,
    review_count: 312,
  },
  {
    id: "demo-type-c-cable-3m",
    slug: "type-c-cable-3m",
    name_en: "Type-C Cable 3M Braided",
    name_bn: "টাইপ-সি ব্রেডেড ক্যাবল ৩M",
    price: 199,
    category: "accessories",
    stock_quantity: 200,
    rating: 4.4,
    review_count: 156,
  },
  {
    id: "demo-car-holder-magnetic",
    slug: "car-holder-magnetic",
    name_en: "Magnetic Car Holder",
    name_bn: "ম্যাগনেটিক কার হোল্ডার",
    price: 399,
    category: "accessories",
    stock_quantity: 40,
    rating: 4.3,
    review_count: 45,
  },
  {
    id: "demo-bt-speaker-waterproof",
    slug: "bt-speaker-waterproof",
    name_en: "Waterproof BT Speaker",
    name_bn: "ওয়াটারপ্রুফ স্পিকার",
    price: 1499,
    original_price: 2000,
    category: "gadgets",
    stock_quantity: 10,
    rating: 4.7,
    review_count: 78,
  },
];

export const DEMO_SERVICES: Service[] = [
  {
    id: "demo-printing-services",
    slug: "printing",
    name_en: "Printing Services",
    name_bn: "প্রিন্টিং সেবা",
    short_description_en: "Business cards, banners, brochures & large format printing.",
    short_description_bn: "বিজনেস কার্ড, ব্যানার, ব্রোশিওর ও লার্জ ফরম্যাট প্রিন্টিং।",
    category: "printing",
    pricing_type: "fixed",
    base_price: 500,
    is_featured: true,
    icon_color: "#1e5ba8",
  },
  {
    id: "demo-legal-assistance",
    slug: "legal",
    name_en: "Legal Assistance",
    name_bn: "আইনি সহায়তা",
    short_description_en: "Government documents, affidavits & legal filings.",
    short_description_bn: "সরকারি ডকুমেন্ট, শপথপত্র ও আইনি কাজ।",
    category: "legal",
    pricing_type: "custom_quote",
    min_price: 1000,
    is_featured: true,
    icon_color: "#f59e0b",
  },
  {
    id: "demo-software-development",
    slug: "software",
    name_en: "Software Development",
    name_bn: "সফটওয়্যার ডেভেলপমেন্ট",
    short_description_en: "Custom web, mobile & enterprise software solutions.",
    short_description_bn: "কাস্টম ওয়েব, মোবাইল ও এন্টারপ্রাইজ সফটওয়্যার সমাধান।",
    category: "software",
    pricing_type: "custom_quote",
    min_price: 25000,
    is_featured: true,
    icon_color: "#16a34a",
  },
  {
    id: "demo-web-design",
    slug: "web-design",
    name_en: "Website Design",
    name_bn: "ওয়েবসাইট ডিজাইন",
    short_description_en: "Modern responsive websites with SEO optimization.",
    short_description_bn: "SEO অপ্টিমাইজড আধুনিক রেসপন্সিভ ওয়েবসাইট।",
    category: "software",
    pricing_type: "package",
    base_price: 15000,
    is_featured: false,
    icon_color: "#7c3aed",
  },
  {
    id: "demo-mobile-app",
    slug: "mobile-app",
    name_en: "Mobile App Development",
    name_bn: "মোবাইল অ্যাপ ডেভেলপমেন্ট",
    short_description_en: "Android & iOS apps for your business.",
    short_description_bn: "আপনার ব্যবসার জন্য অ্যান্ড্রয়েড ও iOS অ্যাপ।",
    category: "software",
    pricing_type: "custom_quote",
    min_price: 50000,
    is_featured: false,
    icon_color: "#0ea5e9",
  },
  {
    id: "demo-digital-marketing",
    slug: "digital-marketing",
    name_en: "Digital Marketing",
    name_bn: "ডিজিটাল মার্কেটিং",
    short_description_en: "Social media, ads & brand growth strategies.",
    short_description_bn: "সোশ্যাল মিডিয়া, বিজ্ঞাপন ও ব্র্যান্ড গ্রোথ স্ট্র্যাটেজি।",
    category: "marketing",
    pricing_type: "package",
    base_price: 8000,
    is_featured: false,
    icon_color: "#ec4899",
  },
];
